### ISSUE TITLE
Six Tests Failing on JRuby because of OpenSSL issue (Original reference #14)

### ISSUE THREAD

**Issue by JanDintel** [digidentity-new/xmlenc#1]
There is an issue with one of the cipher types and JRuby that causes six tests to fail with the same `data hash wrong` exception like this

```
  1) Xmlenc::Algorithms::RsaOaepMgf1p decrypt decrypts the cipher value
     Failure/Error: expect(subject.decrypt(cipher_value)).to be == key
     OpenSSL::PKey::RSAError:
       data hash wrong
     # ./lib/xmlenc/algorithms/rsa_oaep_mgf1p.rb:12:in `decrypt'
     # ./spec/lib/xmlenc/algorithms/rsa_oaep_mgf1p_spec.rb:14:in `(root)'
```

This seems to be [an issue with the default JRuby SSL library](https://github.com/jruby/jruby/issues/1819), and has been patched in the distinct [jruby-ssl](https://github.com/jruby/jruby-openssl/pull/54), but I don't know enough about the issue to either change any dependencies for this gem or make a fix in my local environment to confirm that resolves the issue. I'm noting it here in case you want to investigate or offer and guidance to JRuby users affected by this problem. Thank you.

Original submitter: @harrisj

**Comment by JanDintel** [comment]
The original organisation is restored, including the issues. See: https://github.com/digidentity/xmlenc/issues/14
